//Show one quote /api/quotes/_id-number
GET http://localhost:27017/api/quotes/_id-number HTTP/1.1
content-type: application/json


###

//Show all quotes
GET http://localhost:3000 HTTP/1.1
content-type: application/json



###

//Add a quote -------- /api/quotes
POST http://localhost:27017/api/quotes HTTP/1.1
content-type: application/json

{
    "content": "hej hej hej"
}

###

//Uppdate one quote /api/quotes/_id-number
PUT http://localhost:27017/api/ HTTP/1.1
content-type: application/json

{
    "id": "_id-number",
    "quote": "I'll go if I don't have to walk",
}

###

//Delete a quote /api/quotes/_id-number
DELETE http://localhost:27017/api/quotes/_id-number HTTP/1.1
content-type: application/json

###