//Show one quote /api/quotes/_id-number
GET http://localhost:3000/api/quotes/5eba7cb3156bf32bf4422ce4 HTTP/1.1
content-type: application/json


###

//Show all quotes
# GET http://localhost:3000/api/quotes HTTP/1.1
# content-type: application/json



###

//Add a quote -------- /api/quotes
POST http://localhost:3000/api/quotes HTTP/1.1
content-type: application/json

{
    "content": "hej hej hej",
    "user": "_id: "5eb970f3f870c3c976ef66d9""
}

###

//Uppdate one quote /api/quotes/_id-number
PUT http://localhost:3000/api/quotes/5eba7c9d1350342be05e8671 HTTP/1.1
content-type: application/json

{
    "quote": "I'll go if I don't have to walk",
}

###

//Delete a quote /api/quotes/_id-number
DELETE http://localhost:3000/api/quotes/_id-number HTTP/1.1
content-type: application/json

###
