
//Show all quotes ✅
GET http://localhost:3000/api/quotes HTTP/1.1
content-type: application/json

###

//Show users quotes ✅
GET http://localhost:3000/api/quotes/loggedInUser HTTP/1.1
content-type: application/json

###


//POST ---- CREATE NEW QUOTE ✅
POST http://localhost:3000/api/quotes HTTP/1.1
content-type: application/json

{
    "content": "this is a new quote2"
}

###

//Uppdate one quote /api/quotes/_id-number
PUT http://localhost:3000/api/quotes/ HTTP/1.1
content-type: application/json

{
    "quote": "I'll go if I don't have to walk",
}

###

//Delete a quote /api/quotes/_id-number
DELETE http://localhost:3000/api/quotes/_id-number HTTP/1.1
content-type: application/json

###
