//Show one users   ----/api/users/_id-number
GET http://localhost:3000/api/users/_1 HTTP/1.1

###

//Show all users
GET http://localhost:3000/api/users HTTP/1.1

###


//Add a user -------- /api/usersPOST http://localhost:3000/api/users/createUser HTTP/1.1
POST http://localhost:3000/api/users/createUser HTTP/1.1
content-type: application/json

{
    "name": "claudia",
    "password": "12345"
}

###
###

//Add a user -------- /api/users
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "name": "Kristen Bell",
    "password": "fork"
}

###

