//Show one users   ----/api/users/_id-number
GET http://localhost:3000/api/users/_1 HTTP/1.1

###

//Show all users
GET http://localhost:3000/api/users HTTP/1.1

###

//Add a user -------- /api/users
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "name": "david",
    "password": "1234"
}

###

POST http://localhost:3000/api/users/createUser HTTP/1.1
content-type: application/json

{
    "name": "kattis",
    "password": "12345"
}

###

//Uppdate one user /api/users/_id-number
PUT http://localhost:3000/api/5ebaa49218747737807f537b HTTP/1.1
content-type: application/json

{
 
    "user": "Elaine Benes",
}

###

//Delete a user /api/users/_id-number
DELETE http://localhost:3000/api/users/5ebaa124d7897535ff07c210 HTTP/1.1
content-type: application/json

###